name: Main

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.100"

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: make restore

      - name: Unit tests
        run: make test

      - name: Build & Package
        run: make

      - name: Push packages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.FEEDZ_IO_TOKEN }} --source https://f.feedz.io/nvd/onelogin-aws-cli/nuget/index.json --skip-duplicate
